spring:
  application:
    name: travel-ticket-service
  config:
    import:
      - optional:nacos:travel-ticket-service.yaml
  cloud:
    nacos:
      config:
        enabled: ${NACOS_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:travel-ticket-nacos:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml
        refresh-enabled: true
      discovery:
        enabled: ${NACOS_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:travel-ticket-nacos:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        service: ${spring.application.name}
        cluster-name: ${NACOS_CLUSTER:DEFAULT}
        metadata:
          version: ${APP_VERSION:0.1.0}
          region: ${APP_REGION:local}
